# Generated by Django 4.1.7 on 2024-04-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsblimited', '0003_alter_loanapplication_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
