# Generated by Django 4.1.7 on 2024-04-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsblimited', '0014_alter_loanapplication_loan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.CharField(max_length=100),
        ),
    ]
