# Generated by Django 4.1.7 on 2024-04-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsblimited', '0019_alter_loanapplication_approved_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(default='Applied', max_length=30),
        ),
    ]
